name: Build and Deploy to Testing Server

on:
  workflow_run:
    workflows: ["PHP Mailer Tests"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Export PHP Files
        run: npm run export-php

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_TESTING }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT_TESTING }} -H ${{ secrets.SSH_IP_TESTING }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH to Hostinger
        run: |
          echo "Connecting to Hostinger..."
          ssh -p ${{ secrets.SSH_PORT_TESTING }} ${{ secrets.SSH_USERNAME_TESTING }}@${{ secrets.SSH_IP_TESTING }} << 'EOF'
            rm -rf ${{ secrets.SSH_DEPLOY_DIR }}/*
            exit
          EOF
          
          echo "Uploading files..."
          rsync -avz --delete -e "ssh -p ${{ secrets.SSH_PORT_TESTING }}" ./out/ ${{ secrets.SSH_USERNAME_TESTING }}@${{ secrets.SSH_IP_TESTING }}:${{ secrets.SSH_DEPLOY_DIR }}

          echo "Deployment complete!"

