name: PHP Mailer Tests

on:
  push:
    branches:
      - development
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, xml, ctype, json, curl, dom

      - name: Set Environment Variables
        run: |
          echo "SMTP_USERNAME=divyam.study.work@gmail.com" >> $GITHUB_ENV
          echo "SMTP_PASSWORD=reqwvklemfpqsuyv" >> $GITHUB_ENV

      - name: List Repository Files (Debug)
        run: ls -R

      - name: Start PHP Built-in Server
        run: |
          php -S localhost:8000 -t . > server.log 2>&1 &
          sleep 5  # Wait for the server to start

      - name: Run PHP Mail Test
        run: php tests/MailTest.php
